PROGRAM mulitdim_array_demo
      ! This program demonstrates manipulation of multiarray in C/C++
      IMPLICIT NONE

      COMPLEX(kind=4) :: N = (10,10)
      COMPLEX(kind=8) :: M = (10,10)
      
      
      ! call C/C++ function directly by its name generated by C compiler
      ! without use of any defined Fortran interafece
      CALL cmplx_print(N)
      CALL cmplx_print(M)
END PROGRAM mulitdim_array_demo
