PROGRAM mulitdim_array_demo
      ! This program demonstrates manipulation of multiarray in C/C++
      IMPLICIT NONE
      INTEGER, PARAMETER :: N = 10
      COMPLEX(kind=8) :: M = (10,10)
      COMPLEX(kind=8), DIMENSION(N, N) :: A
      INTEGER :: I,J
      
      DO I=1, N
        DO J=1, N
          A(I,J) = cmplx(I,J)
        END DO
      END DO
      
      ! call C/C++ function directly by its name generated by C compiler
      ! without use of any defined Fortran interafece
      CALL cmplx_print(M)
      CALL cmplx_print_arr(A, N)
END PROGRAM mulitdim_array_demo
