PROGRAM mulitdim_array_demo
      ! This program demonstrates manipulation of multiarray in C/C++
      IMPLICIT NONE

      INTEGER, PARAMETER :: N = 10
      INTEGER, PARAMETER :: M = 15
      INTEGER, PARAMETER :: K = 15
      INTEGER :: I
      INTEGER, DIMENSION(N, M) :: A = RESHAPE((/ (I, I=1, N*M) /), [N, M])
      INTEGER, DIMENSION(N, M, N) :: B = RESHAPE((/ (I, I=1, N*M*N) /), [N, M, N])
      INTEGER, DIMENSION(N, M, N, K) :: C = RESHAPE((/ (I, I=1, N*M*N*K) /), [N, M, N, K])
      
      
      ! call C/C++ function directly by its name generated by C compiler
      ! without use of any defined Fortran interafece
      CALL arr_print(A, N, M)
      CALL arr_print3d(B, N, M, N)
      CALL arr_print4d(C, N, M, N, K)
END PROGRAM mulitdim_array_demo
